% Load the data generated by p2simulation
function collatedFiringRates = p2loaddata(trials)

	for i = 1:trials

		load(sprintf('data/p2data%d.mat',i));
		collatedFiringRates{i} = firingRates{i};

	end

end