function collatedFiringRates = p2loaddata(trials)
	% Load the data generated by p2simulation

	for i = 1:trials

		load(sprintf('data/p2data%d.mat',i));
		collatedFiringRates{i} = firingRates{i};

	end

end